baseURL = "https://yaahua.github.io/blogyaahua/"
languageCode = "zh-hans-cn"
defaultContentLanguage = "zh-hans-cn"
title = "Yaahua 的博客"
theme = "hugo-theme-stack"
hasCJKLanguage = true
paginate = 10

[languages]
  [languages.zh-hans-cn]
    languageName = "简体中文"
    weight = 1

    [languages.zh-hans-cn.params]
      description = "反思、日记、学史杂记、创作"

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  post = "/p/:slug/"
  page = "/:slug/"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = -100
    [menu.main.params]
      icon = "home"
      newTab = false

  [[menu.main]]
    identifier = "about"
    name = "关于我"
    url = "/about/"
    weight = -90
    [menu.main.params]
      icon = "user"
      newTab = false

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = -70
    [menu.main.params]
      icon = "archives"
      newTab = false

  [[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = -60
    [menu.main.params]
      icon = "search"
      newTab = false

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 4
    ordered    = false

  [markup.highlight]
    lineNos = true
    noClasses = false

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
